# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Kunbang boundary', kernelModule='Horizontal_kinematic_constraints', kernelFunction='main', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgLabel(p='DialogBox', text='Author: sh-wx BJUT', useBoldFont=True)
RsgLabel(p='DialogBox', text='Use after meshing the part', useBoldFont=True)
RsgComboBox(name='ComboBox_2', p='DialogBox', text='Part:', keyword='PartName', default='', comboType='MDB', repository='parts', rootText='Model:', rootKeyword='Modelname', layout='HORIZONTAL')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Instance name:', keyword='instancename', default='Part-1-1')
RsgComboBox(name='ComboBox_5', p='DialogBox', text='Vertical direction(Only 3D):', keyword='verticaldirection', default='Y', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_5', text='Y')
RsgListItem(p='ComboBox_5', text='Z')
RsgIcon(p='DialogBox', fileName=r'1.png')
osutils.copy(os.path.join(thisDir,r'1.png'), dialogBox.execDir, force=True)
dialogBox.show()